server: 
  port: 9527
 
spring: 
  application:
    name: foodie-zuul-gateway
 
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: foodie-zuul
    prefer-ip-address: true 
 
 
zuul:
#  sensitive-headers: Access-Control-Allow-Origin
#  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  #ignored-services: microservicecloud-dept
  #prefix: /atguigu
  ignored-services: "*"
  routes:
    user:
      serviceId: foodie-user-consumer
      path: /user/**
    shop:
      serviceId: foodie-shop-consumer
      path: /shop/**
    operator:
      serviceId: foodie-operator-consumer
      path: /operator/**

#    dishes:
#      serviceId: foodie-shopdishes
#      path: /dishes/**

info:
  app.name: lanke-foodie
  company.name: www.lanke.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$