mybatis:
 # config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.lanke.foodie.entity    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:/mapper/*.xml                       # mapper映射文件

spring:
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://39.96.169.46:3306/foodie_shop?useUnicode=true&characterEncoding=utf-8             # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间



ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000